# Generated by Django 3.0.8 on 2020-07-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcss', '0002_auto_20200729_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldcategory',
            name='on_csrankings',
        ),
        migrations.AddField(
            model_name='conference',
            name='on_csrankings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='publications',
            field=models.ManyToManyField(blank=True, to='kcss.Publication'),
        ),
    ]
