# Generated by Django 3.0.8 on 2020-07-30 06:55

from django.db import migrations, models
import kcss.models


class Migration(migrations.Migration):

    dependencies = [
        ('kcss', '0004_auto_20200729_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='published_years',
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(validators=[kcss.models.min_year_validator, kcss.models.max_year_validator]),
        ),
    ]
