# Generated by Django 3.0.8 on 2020-07-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcss', '0005_auto_20200730_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
