# Generated by Django 3.0.8 on 2020-07-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcss', '0006_auto_20200731_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['field_category', 'conf_name']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='publications',
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(to='kcss.Author'),
        ),
    ]
