# Generated by Django 3.0.8 on 2020-07-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcss', '0007_auto_20200731_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcss.Author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcss.Publication')),
            ],
            options={
                'ordering': ['publication', 'number'],
            },
        ),
    ]
