# Generated by Django 3.0.8 on 2020-07-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcss', '0008_auto_20200731_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(through='kcss.PublicationAuthor', to='kcss.Author'),
        ),
    ]
