# Generated by Django 3.0.8 on 2020-08-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcss', '0009_publication_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicationAuthor',
            new_name='Coauthorship',
        ),
    ]
