# Generated by Django 3.0.8 on 2020-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcss', '0010_auto_20200802_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='coauthorship',
            unique_together={('publication', 'author', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together={('conf', 'year', 'title')},
        ),
    ]
