# Generated by Django 3.0.8 on 2020-08-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcss', '0011_auto_20200802_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(db_index=True, through='kcss.Coauthorship', to='kcss.Author'),
        ),
    ]
