# Generated by Django 3.0.8 on 2020-08-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcss', '0012_auto_20200803_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(db_index=True, related_name='publications', through='kcss.Coauthorship', to='kcss.Author'),
        ),
    ]
