# Generated by Django 3.0.8 on 2020-08-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcss', '0013_auto_20200809_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coauthorship',
            options={'ordering': ['publication', 'author_order']},
        ),
        migrations.RenameField(
            model_name='coauthorship',
            old_name='number',
            new_name='author_order',
        ),
        migrations.AlterUniqueTogether(
            name='coauthorship',
            unique_together={('publication', 'author', 'author_order')},
        ),
    ]
